import React from "react";
import { Layout } from "components/Layout";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { ArrowLeft } from "lucide-react";
import { useNavigate } from "react-router-dom";

export default function PrivacyPolicy() {
  const navigate = useNavigate();
  
  return (
    <Layout>
      <div className="container py-6 max-w-4xl mx-auto">
        <Button 
          variant="ghost" 
          className="mb-4" 
          onClick={() => navigate(-1)}
        >
          <ArrowLeft className="mr-2 h-4 w-4" /> Back
        </Button>
        
        <Card>
          <CardHeader>
            <CardTitle className="text-2xl font-bold">Privacy Policy for QR Ninja</CardTitle>
          </CardHeader>
          <CardContent className="prose max-w-none">
            <p><strong>Effective Date:</strong> April 14, 2025</p>
            
            <p>This Privacy Policy describes how QR Ninja ("we", "our", or "us") collects, uses, stores, and shares information in connection with your use of our application ("App") available on the BigCommerce platform.</p>
            
            <h2 className="text-xl font-bold mt-6 mb-3">Information We Collect</h2>
            
            <p>QR Ninja collects and processes the following types of information:</p>
            
            <ul className="list-disc pl-6 space-y-2">
              <li><strong>Anonymous Usage Data:</strong> We collect aggregated and anonymous statistics about the number of scans of QR codes generated by the App. This data does not include any personally identifiable information about end users.</li>
              <li><strong>QR Code Configurations:</strong> We store information regarding the configuration of QR codes you generate, including destination URLs, colors, text, markers, logos, and related settings.</li>
            </ul>
            
            <h2 className="text-xl font-bold mt-6 mb-3">Purpose of Data Collection</h2>
            
            <p>We collect and use this data solely for:</p>
            
            <ul className="list-disc pl-6 space-y-2">
              <li>Managing and customizing your QR codes effectively.</li>
              <li>Providing analytics and insights into the performance of your QR codes, helping you optimize your marketing campaigns.</li>
            </ul>
            
            <h2 className="text-xl font-bold mt-6 mb-3">Data Storage and Security</h2>
            
            <p>All collected data is securely stored in encrypted databases hosted on secure servers. Sensitive information is encrypted to protect against unauthorized access, alteration, disclosure, or destruction.</p>
            
            <h2 className="text-xl font-bold mt-6 mb-3">Data Retention Period</h2>
            
            <p>Your data is stored as long as your store continues using QR Ninja or until you request data deletion. Upon your request or uninstallation of the App, your data will be permanently deleted within 30 days, unless retention is required by law.</p>
            
            <h2 className="text-xl font-bold mt-6 mb-3">User Rights</h2>
            
            <p>Under GDPR and CCPA regulations, you have the right to:</p>
            
            <ul className="list-disc pl-6 space-y-2">
              <li>Access the data we store about you.</li>
              <li>Request correction of incorrect or incomplete data.</li>
              <li>Request deletion of your data from our systems.</li>
              <li>Object to or restrict processing of your data under certain circumstances.</li>
            </ul>
            
            <p>To exercise these rights, please contact us via the details provided below.</p>
            
            <h2 className="text-xl font-bold mt-6 mb-3">Contact Information</h2>
            
            <p>For any privacy-related questions, concerns, or requests, please contact:</p>
            
            <p className="whitespace-pre-line font-medium">
              Get Robo
              Stefana Banacha 29a/54
              31-235 Cracow
              Poland
              info@getrobo.xyz
            </p>
            
            <h2 className="text-xl font-bold mt-6 mb-3">Compliance with Regulations</h2>
            
            <p>We comply with all applicable privacy laws, including the General Data Protection Regulation (GDPR) and the California Consumer Privacy Act (CCPA). Our practices are designed to protect your privacy and provide transparency in our data handling.</p>
            
            <h2 className="text-xl font-bold mt-6 mb-3">Changes to this Privacy Policy</h2>
            
            <p>We may update this Privacy Policy from time to time. We will notify you about significant changes by updating the "Effective Date" at the top of this policy and through notifications within the App or via email.</p>
            
            <p>By using QR Ninja, you agree to this Privacy Policy.</p>
            
            <p>Thank you for choosing QR Ninja!</p>
          </CardContent>
        </Card>
      </div>
    </Layout>
  );
}
