
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";



const App = lazy(() => import("./pages/App.tsx"));
const AppManifest = lazy(() => import("./pages/AppManifest.tsx"));
const CustomizeQRVisuals = lazy(() => import("./pages/CustomizeQRVisuals.tsx"));
const DefineQRDetails = lazy(() => import("./pages/DefineQRDetails.tsx"));
const EditQr = lazy(() => import("./pages/EditQr.tsx"));
const HelloWorld = lazy(() => import("./pages/HelloWorld.tsx"));
const InstallationConfirmation = lazy(() => import("./pages/InstallationConfirmation.tsx"));
const InstallationGuide = lazy(() => import("./pages/InstallationGuide.tsx"));
const MyQrCodes = lazy(() => import("./pages/MyQrCodes.tsx"));
const NewQr = lazy(() => import("./pages/NewQr.tsx"));
const PrivacyPolicy = lazy(() => import("./pages/PrivacyPolicy.tsx"));
const ProductBrowser = lazy(() => import("./pages/ProductBrowser.tsx"));
const Products = lazy(() => import("./pages/Products.tsx"));
const ProductsPage = lazy(() => import("./pages/ProductsPage.tsx"));
const QRGenerationTest = lazy(() => import("./pages/QRGenerationTest.tsx"));
const SaveAndDownloadQR = lazy(() => import("./pages/SaveAndDownloadQR.tsx"));
const SelectQRType = lazy(() => import("./pages/SelectQRType.tsx"));
const Settings = lazy(() => import("./pages/Settings.tsx"));
const Stats = lazy(() => import("./pages/Stats.tsx"));
const TermsOfService = lazy(() => import("./pages/TermsOfService.tsx"));
const UserGuide = lazy(() => import("./pages/UserGuide.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/", element: <App />},
	{ path: "/app-manifest", element: <AppManifest />},
	{ path: "/appmanifest", element: <AppManifest />},
	{ path: "/customize-qr-visuals", element: <CustomizeQRVisuals />},
	{ path: "/customizeqrvisuals", element: <CustomizeQRVisuals />},
	{ path: "/define-qr-details", element: <DefineQRDetails />},
	{ path: "/defineqrdetails", element: <DefineQRDetails />},
	{ path: "/edit-qr", element: <EditQr />},
	{ path: "/editqr", element: <EditQr />},
	{ path: "/hello-world", element: <HelloWorld />},
	{ path: "/helloworld", element: <HelloWorld />},
	{ path: "/installation-confirmation", element: <InstallationConfirmation />},
	{ path: "/installationconfirmation", element: <InstallationConfirmation />},
	{ path: "/installation-guide", element: <InstallationGuide />},
	{ path: "/installationguide", element: <InstallationGuide />},
	{ path: "/my-qr-codes", element: <MyQrCodes />},
	{ path: "/myqrcodes", element: <MyQrCodes />},
	{ path: "/new-qr", element: <NewQr />},
	{ path: "/newqr", element: <NewQr />},
	{ path: "/privacy-policy", element: <PrivacyPolicy />},
	{ path: "/privacypolicy", element: <PrivacyPolicy />},
	{ path: "/product-browser", element: <ProductBrowser />},
	{ path: "/productbrowser", element: <ProductBrowser />},
	{ path: "/products", element: <Products />},
	{ path: "/products-page", element: <ProductsPage />},
	{ path: "/productspage", element: <ProductsPage />},
	{ path: "/qr-generation-test", element: <QRGenerationTest />},
	{ path: "/qrgenerationtest", element: <QRGenerationTest />},
	{ path: "/save-and-download-qr", element: <SaveAndDownloadQR />},
	{ path: "/saveanddownloadqr", element: <SaveAndDownloadQR />},
	{ path: "/select-qr-type", element: <SelectQRType />},
	{ path: "/selectqrtype", element: <SelectQRType />},
	{ path: "/settings", element: <Settings />},
	{ path: "/stats", element: <Stats />},
	{ path: "/terms-of-service", element: <TermsOfService />},
	{ path: "/termsofservice", element: <TermsOfService />},
	{ path: "/user-guide", element: <UserGuide />},
	{ path: "/userguide", element: <UserGuide />},

];
